### ISSUE TITLE
No support for auth?

### ISSUE THREAD

**Issue by jlsjonas** [pm2-hive/pm2-elasticsearch#4]
undescriptive error (from JSON.parse) when using authentication

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/home/jonas/.pm2/node_modules/pm2-elasticsearch/app.js:60:23)
    at Request.self.callback (/home/jonas/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/jonas/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/jonas/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
```

**Comment by vmarchaud** [comment]
The module has been re-wrote, you can now use auth for connection, see the readme ;)
